title: b00bl1k
author: b00bl1k
email: 6006l1k@gmail.com
description: "My personal blog"
baseurl: ""
twitter_username: 6006l1k
github_username: b00bl1k
google_analytics: UA-42973733-4

# Build settings
markdown: kramdown
theme: minima
