title: b00bl1k's blog
author: b00bl1k
email: 6006l1k@gmail.com
description: "My personal blog"
lang: ru_RU
twitter_username: 6006l1k
github_username: b00bl1k
google_analytics: UA-42973733-4
show_excerpts: true

twitter:
  username: 6006l1k
  card: summary

markdown: kramdown
theme: minima
