title: b00bl1k's blog
author: b00bl1k
email: 6006l1k@gmail.com
description: ""
baseurl: ""
twitter_username: 6006l1k
github_username: b00bl1k
disqus:
    shortname: b00bl1k

# Build settings
markdown: kramdown
theme: minima
